### ISSUE TITLE
Help on user input

### ISSUE THREAD

**Issue by alatorre-sebastian** [caleb531/automata#118]
Hi im traying to build a program that let you introduce your own NFA and transform it to DFA.
I would like to recive some advice

So I would like to know what would be the best option for **TRANSITIONS** user input.
![image](https://user-images.githubusercontent.com/112382473/206905667-fc876c11-c4d4-4c49-909e-7d30f2606f45.png)
**(In the case where the symbol is repeated)**

I have someting like this but it doesn't work, cause how dicts works.
In a while:
transitions_aux ={
            input('State?: '): { input('value: '): set(input('transitionState:').split()) },
            }
        transitions.update(transitions_aux)

Should the user be ask just for a string instead?

Sorry for bad english.

**Comment by caleb531** [comment]
@alatorre-sebastian Well, you would need to create an empty dictionary from the start and incrementally build it up as you request input. The top-level dictionary will have as many keys as there are states, and the number of keys in each sub-dictionary will equal the number of input symbols you have.

This is because, unless you pass `allow_partial=True` to your DFA on instantiation, every DFA state must have a transition for every input symbol. So your code should be something like the following (if you leave `allow_partial` as the default value of `False`).

```python
states_aux = {'q0', 'q1', 'q2'}
input_symbols_aux = {'a', 'b'}
transitions_aux = {}
for start_state in states_aux:
    transitions_aux[start_state] = {}
    for symbol in input_symbols_aux:
        end_state = input(f'Reading symbol {symbol} on state {start_state} should move to state:')
        transitions_aux[start_state][symbol] = end_state
```

**Comment by caleb531** [comment]
@alatorre-sebastian Closing this issue now unless you have further questions (please let me know if you do!).
