### ISSUE TITLE
Allow Turing Machine input set to be equal to the tape symbol set

### ISSUE THREAD

**Issue by NonlinearFruit** [caleb531/automata#127]
Right now the input symbols _has_ to be a proper subset of the tape symbols (link below). But in our case we would like to have the input equal the allowed tape symbols.

This worked for us locally
```py
    def _read_input_symbol_subset(self):
        if not (self.input_symbols <= self.tape_symbols):
            raise exceptions.MissingSymbolError(
                'The set of tape symbols is missing symbols from the input '
                'symbol set ({})'.format(
                    self.tape_symbols - self.input_symbols))
```

https://github.com/caleb531/automata/blob/main/automata/tm/tm.py#L14

**Comment by NonlinearFruit** [comment]
Just noticed that there is a dtm test for `test_validate_input_symbol_subset` that is forcing the input set to be a proper subset of the tape symbol set.

Is there a reason to disallow these sets being equal?
```py
DTM(
  input_symbols =  {'0', '1'},
  tape_symbols = {'0', '1'}
  ...
)
```

**Comment by caleb531** [comment]
@NonlinearFruit This restriction is actually in accordance with the definition of a Turing machine, which requires the presence of a blank symbol. Per the definition, this blank symbol must belong to the set of tape symbols but _cannot_ also be an input symbol (see sources below).

I am not sure the specific use case you are trying to achieve in your program, but you _must_ define a `blank_symbol` because that's part of what makes a Turing machine a Turing machine.

Still, I want you to thank you for bringing this up because it keeps me accountable for ensuring that this library properly implements the underlying theory.

Sources:
- https://cs.stackexchange.com/questions/108983/why-is-the-blank-symbol-not-considered-part-of-the-input-alphabet-of-a-turing-ma
- https://cs.stackexchange.com/questions/79761/how-can-blank-be-written-on-the-tape-if-it-is-not-part-of-input-alphabet

**Comment by NonlinearFruit** [comment]
Nice! I didn't know that. Thank you for the resources and taking the time to educate me 😁 

I love the library. I'm using it to TDD some Turing Machines which has been super fun
