### ISSUE TITLE
How to express the empty string in regexes?

### ISSUE THREAD

**Issue by kach** [caleb531/automata#128]
Is there a way to specify the empty string as part of regexes? For example, Python's built-in re.compile allows expressions like `'()'` or `'|'`, but the parser in this library throws an error on both.

**Comment by caleb531** [comment]
@kach I don't believe this is supported currently. @eliotwrobson how feasible do you think this would be to implement?

**Comment by eliotwrobson** [comment]
I think there's some subtlety to this but it _should_ be straightforward? The only issue is making sure it doesn't create weird regex inconsistencies with some edge cases (i.e. looking at the empty string vs the empty language). However, I think that this should be handled after https://github.com/caleb531/automata/pull/121 gets taken care of, since that PR would change the way some defaults are set (which in turn, would affect how this would work). The main obstacle to that is some pending discussion @caleb531.

@kach As a workaround for now, I think there should be a way to make an NFA that accepts only the empty string with one of the built-in creation functions (may require converting from DFA to NFA). If there isn't I can send you the code for this, since it's very short. What use cases are you working with for this library?

**Comment by kach** [comment]
I am looking to procedurally/recursively iterate over the set of all regexes. The definition of regex I'm following builds them inductively from six ingredients: empty regex, empty string, single symbol, concatenation, alternation, and Kleene star. I don't care about the empty regex (that can be a special case), but it would be nice to be able to represent empty string.

**Comment by eliotwrobson** [comment]
That seems reasonable. Could you try `NFA.from_regex('')` and see if that does what you need? Look at the code again I think that might just work.

**Comment by kach** [comment]
`NFA.from_regex('')` indeed works, but that is only the special case of empty string itself. There doesn't seem to be a way to use empty string as part of a larger regex. For example, I'm not sure how to express `(a|)`, which matches either "a" or the empty string (without using the `?` special form, of course— but I am trying to avoid using `?` because it is not part of the formalism I mentioned above, but rather "syntactic sugar" for something that should already be expressible).

**Comment by eliotwrobson** [comment]
@kach Ah, I see what you mean. Right now, having the consecutive parenthesis `()` is disallowed, so it should be no problem to change that to parse into the empty string. It's a little trickier to have `(a|)` parse into `a?` because of how the `|` operator is set up.

**Comment by kach** [comment]
Changing () to parse to empty string would be excellent! I am okay with writing (a|()) instead of (a|). :)

**Comment by eliotwrobson** [comment]
@caleb531 @kach this issue can be closed now, as the feature was merged to `develop` in the linked PR.

**Comment by caleb531** [comment]
@eliotwrobson Roger. Closing this PR now.

**Comment by kach** [comment]
Amazing! Thank you!!
