### ISSUE TITLE
`validate` return type

### ISSUE THREAD

**Issue by eliotwrobson** [caleb531/automata#135]
@caleb531 looking at the code again, I observed that the `validate` function either raises an exception (in the fail case) or returns `True` (if validation succeeded). I think that the return type should be omitted, since no exception being raised informs the client code that validation has succeeded, and the existing return value can always be discarded. I think the situation is similar to that described here: https://stackoverflow.com/questions/61304761/is-it-good-practice-to-return-true-when-success-otherwise-raise-exception-in-pyt

**Comment by caleb531** [comment]
@eliotwrobson 

## To return or to have side effects?

When you say "the return type should be omitted", it sounds like you mean to rid of the `return True` altogether and have the function either (implicitly) return `None` _or_ raise an exception. If that is what you mean (as opposed to merely omitting the annotation), that does sense to me, since I am have tried to employ the following principle in my own development:

> A function should either return a value, or have side effects, but not both.

Now, in the context of Python, I do not consider raising an exception to be a side effect that breaks this rule, as it is a common pattern used in the Python stdlib and elsewhere.

## Implicitly returning `None` / no return statement makes sense

However, I do agree that returning a constant value like `True` feels a bit useless. I think it was a decision I made when I originally wrote the library, and I suppose it just stuck around all these years. And while it does make testing a little easier (there is no `assertNotRaises` assertion in Python), there are decent alternatives (such as checking if the return type is implicitly `None`, if we are okay with the tests caring about the return value in the first place).

If we implicitly return `None`, it _would_ technically be a breaking change, albeit a minor one. The only case I can think of where that could break someone's code is if they are calling `validate()` as the condition of an `if` block, and therefore are relying on a truthy value being returned for the condition to pass. But they probably shouldn't be doing that anyway, since in the case of an invalid machine, an exception is raised rather than `False` being returned. So the correct usage would only ever be calling the method in a `try..except` and without capturing the return value.

## Public or private?

And with the recent immutability changes, `validate()` has (in many ways) effectively become more of a private method (although technically still not, since we added a global option to re-enable mutability, so allowing the user to call the method may still be useful).

**Comment by eliotwrobson** [comment]
@caleb531 yes, you phrased it better than I did. Effectively this would just be removing the `return True` line at the end of each validate function. And while it would _technically_ be a breaking change, code relying on that behavior would need to be in a `try..except` block to work correctly.

**Comment by caleb531** [comment]
@eliotwrobson Agreed. And closing this issue now that #137 has been merged.
