### ISSUE TITLE
Feature request: Supporting transition with logical operations on input symbols

### ISSUE THREAD

**Issue by mhtb32** [caleb531/automata#17]
I propose adding the functionality to define transition rules which are a logical combination of the input symbols, like:

```Python
from automata.fa.dfa import DFA

dfa = DFA(
    states={'q0', 'q1'},
    input_symbols={'x', 'y'},
    transitions={
        'q0': {'x': 'q0', '!x': 'q1'},  # go to q1 if neg x
        'q1': {'x & y': 'q0', 'y': 'q1'}  # go to q1 if x and y
    },
    initial_state='q0',
    final_states={'q1'}
)

print(dfa.read_input('!xy(x & y)'))  # produces q0

```

One idea for implementation would be to use parser generator libraries such as the good old [PLY](https://github.com/dabeaz/ply) or its new refreshed version, [SLY](https://github.com/dabeaz/sly).

**Comment by caleb531** [comment]
@mhtb32 I appreciate the feature suggestion, however this feels too domain-specific. It would require completely rewriting the way the input is currently parsed (since you are no longer iterating character by character, but are dealing with sequences of characters and evaluating those chunks).

However, it seems like it should (in theory) be possible to create a subclass on the existing `DFA` class to introduce this supplemental functionality. To do that, you would first need to find a formal DFA which is equivalent to the specialized DFA you provided above. Then, you could use those two DFAs to aid you in writing your subclass, whereby you accept a specialized DFA as input, convert it to a formal DFA, and feed that formal DFA to my existing `DFA` class methods.
