### ISSUE TITLE
Get back the old default method to compute the input symbols

### ISSUE THREAD

**Issue by EduardoGoulart1** [caleb531/automata#185]
Hi there! Before, when performing `NFA.from_regex`, the input symbols were computed to be the set of non-reserved characters of the expression. With [this PR](https://github.com/caleb531/automata/pull/121), this was changed to all the ASCII characters + the digits.

For my application, I have multiple regular expressions that are specified. It is unergonomic (and error-prone) to keep specifying the alphabet every time. Is there a chance that we bring back the old behavior?

I am not sure why this was first changed. Was it to avoid some conflict in the parser?

**Comment by eliotwrobson** [comment]
This was originally changed to avoid issues where input symbols were being included that weren't being used as part of the expression. But this also has the side effect that the default alphabet is the same between converting different regexes, which means avoiding alphabet mismatch issues between NFAs made using default arguments.

I'm not inherently opposed to changing the above, but I think avoiding alphabet mismatch issues for users at the cost of some people needing to specify the alphabet is a worthwhile tradeoff.

**Comment by EduardoGoulart1** [comment]
In general, I agree, but I am concerned about two aspects:

1. Relates to performance. Keeping a large transition function where many characters are not needed is a bit of a waste
2. The choice of characters is a bit arbitrary. I would argue that unless we are considering the case of generating ASCII strings, there is no reason why the ASCII alphabet should be the default

If we consider partial DFAs, then mismatching alphabets are not a problem. The only problem is to interpret the `.` symbol. In that case, I would argue that if `.` should include symbols that are not part of the regex, then the user should explicitly specify it.

**Comment by eliotwrobson** [comment]
@EduardoGoulart1 with respect to performance, the parser only creates additional transitions when using the wildcard character (as NFAs follow similar rules to partial DFAs), and anyone running into performance issues can always restrict the alphabet.

The ascii alphabet is the default because characters are currently restricted to ascii letters and digits in the parser. This support may be expanded later but using this as a default is mainly to reduce confusion. Otherwise, the character set depends on the input in weird ways.

**Comment by EduardoGoulart1** [comment]
Ok closing this here... Seems like other libraries also do it like that
