### ISSUE TITLE
show_diagram for Non-DFAs

### ISSUE THREAD

**Issue by justkrismanohar** [caleb531/automata#41]
DFAs have show diagram. 
Expected NFAs an other machinces to have similar funtionality.

**Comment by caleb531** [comment]
@justkrismanohar I don't want visualization to be a primary focus of this library; I would certainly recommend @lewiuberg's project if you need more visualization capabilities.

Currently, the DFA is the only class with visualization capability (because, as I recall, someone submitted me a PR, and I thought to myself, "Why not?"). However, in hindsight, I think it would've been better to leave all visualization capabilities to other libraries, such that my library can remain focused on the data structures themselves.

Granted, I don't plan to remove the `DFA.show_diagram()` method for backwards-compatibility (*and* lest I alienate my users who rely on the functionality).
