### ISSUE TITLE
Regex parsing efficiency

### ISSUE THREAD

**Issue by eliotwrobson** [caleb531/automata#61]
In looking at the current regex parser, it seems like it could be made significantly faster with a more robust implementation (i.e. use specialized classes to reduce overhead when applying the NFA creation operations). We're working on a fast regex parser for our course (since we need to parse large regexes). Would there be interest in adapting a version for integration with this library?

**Comment by caleb531** [comment]
@eliotwrobson I would certainly be open to it! By "adapting a version for integration with this library", do you mean that the faster regex implementation would be part of this library's codebase (as opposed to adding another dependency)?

**Comment by caleb531** [comment]
@eliotwrobson Okay, that sounds great! I don't have anything to suggest from an architecture perspective, since I don't want to put arbitrary restrictions on your ability to implement these optimizations.

So with that, I will happily review any PRs you send my way! And if I spot anything I'd like to discuss, we can take up the discussion there.

**Comment by caleb531** [comment]
@eliotwrobson Even though I've merged your PR #62, I plan to keep this issue open until I release the functionality into `main`.
